### ISSUE TITLE
Posting images

### ISSUE THREAD

**Issue by mmartinortiz** [binokochumolvarghese/lightbi-hugo#67]
Hi,

When I try to add an extra image to my posts, the image appears as a broken link. I've used the markdown syntax as the [figure shortcut](https://github.com/binokochumolvarghese/lightbi-hugo/wiki/Shortcodes#image-with-caption), but none of them worked.

In [this sample page](https://lightbi-hugo-theme.netlify.app/post/2020/jan/syntax/) the image also appears as a broken link.

**Comment by binokochumolvarghese** [comment]
Use `{{< figure src="/path/to/image.jpg" caption="Caption for Image" attrlink="" >}}`. It should work, please check your images are in the asset folder or not.

**Comment by mmartinortiz** [comment]
Thanks for your answer.

Using `{{< figure ... >}}` does not work either. I have pushed the suggested change to [this branch of my website](https://github.com/mmartinortiz/website/tree/fix-image-not-shown). The modified file is [this one](https://github.com/mmartinortiz/website/blob/fix-image-not-shown/content/projects/rgb-flowers.md), and all the images are under the [/assets/img](https://github.com/mmartinortiz/website/tree/fix-image-not-shown/assets/img) folder.

I tried multiple combinations for the image path:

- `/img/rgb-flowers-2.jpg`
- `img/irgb-flowers-2.jpg`
- `/assets/img/rgb-flowers-2.jpg`
- `assets/img/rgb-flowers-2.jpg`

If I understood correctly, the documentation indicates that `/assets` is not required, and the absolute path needs to start right after `/assets`.

**Comment by binokochumolvarghese** [comment]
Can you please take the latest theme and try.

**Comment by mmartinortiz** [comment]
After

```bash
git submodule update --recursive --remote
```

I get the following error:

> Error: error building site: render: failed to render pages: render of "section" failed: "/home/user/Projects/website/themes/lightbi-hugo/layouts/about/about.html:8:27": execute of template failed: template: about/about.html:8:27: executing "main" at <$image.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink

If I clone the demo website, the same error does not show up. I noticed that the theme is under a different folder.

My `.gitsubmodule`

```
[submodule "themes/lightbi-hugo"]
    path = themes/lightbi-hugo
    url = https://github.com/binokochumolvarghese/lightbi-hugo
```

Demo's website `.gitsubmodule`

```
[submodule "themes/themes/lightbi-hugo"]
    path = themes/themes/lightbi-hugo
    url = https://github.com/binokochumolvarghese/lightbi-hugo
```

Is it relevant?

Even though, in the demo website the post **Markdown Syntax Guide**, which contains an image, the image is not rendered in the post.

**Comment by binokochumolvarghese** [comment]
I downloaded the theme locally and its running fine. Can you try that also? Also the figure shortcode is working in the [demo](https://lightbi-hugo-theme.netlify.app/post/2020/jan/shortcodes/). You can try that.

When the  images are taking from the assets folder Markdown Syntax is not working, I will check the same.

**Comment by mmartinortiz** [comment]
I just cloned the theme and copied it inside my website's `themes` folder. The error about the pointer is gone, but the images are still not displayed. I used exactly the syntax of the demo, including some variants with the paths:

```
{{< figure src="/img/epuck.jpg" caption="With caption." attrlink="" >}}
{{< figure src="img/rgb-flowers-2.jpg" caption="Caption for Image" attrlink="" >}}
{{< figure src="/img/rgb-flowers-2.jpg" caption="Caption for Image" attrlink="" >}}
{{< figure src="assets/img/rgb-flowers-2.jpg" caption="Caption for Image" attrlink="" >}}
{{< figure src="/assets/img/rgb-flowers-2.jpg" caption="Caption for Image" attrlink="" >}}
```

An important difference I noticed between the demo and my website, is that the images are located in different places:

- My website has all the images under the `assets/img` folder. The images here are found and used as the main picture of the post, the keyword `image` used by Hugo.
- The demo has the image `/img/posts/img-3.jpg` on two different locations: Under `themes/lightbi-hugo/assets` and `public`

In my website I've defined in the `hugo.toml` file the location of `staticDirs` under `["static", "assets"]`, but the demo site does not define the `staticDirs` variable.

**Comment by binokochumolvarghese** [comment]
Hope the issue is resolved in the latest update.

**Comment by mmartinortiz** [comment]
Thanks for bringing my attention back to this issue. I updated the submodule with the theme and the issue remains the same.

How could I easily start locally the example site?

**Comment by binokochumolvarghese** [comment]
Can you check this [link](https://lightbi-hugo-theme.netlify.app/en/post/2020/use-this-theme/). I have updated the theme installation details

**Comment by mmartinortiz** [comment]
Locally now it loads the images and the gallery is also working, thanks!

However, the post's image is not rendered. The same happens with the example website. For example, `features-of-lightbi.md` is defined as follows:

```md
---
title: Features of Lightbi
date: 2023-12-20
tags: ["hugo","blog"]
image : "/img/posts/img-2.jpg"
Description  : "In this blog post, I’ll walk through the key features of the Lightbi theme and how to make the most of them for a visually appealing, user-friendly website."
featured: true
---
```

The card shows the image "img-2.jpg" but not the page itself (that was the previous behaviour)

Additionally, the GitHub action is failing with the following error:

```
Error: error building site: render: failed to render pages: render of "page" failed: "/home/runner/work/website/website/themes/lightbi-hugo/layouts/_default/baseof.html:7:7": execute of template failed: template: _default/single.html:7:7: executing "_default/single.html" at <partial "nav.html" .>: error calling partial: "/home/runner/work/website/website/themes/lightbi-hugo/layouts/partials/nav.html:45:18": execute of template failed: template: partials/nav.html:45:18: executing "partials/nav.html" at <hugo>: can't evaluate field IsMultilingual in type interface {}
```

**Comment by binokochumolvarghese** [comment]
In the new theme image in the post is hided by default. You can use the parameter `hidePostImage` as true.

**Comment by mmartinortiz** [comment]
I missed that parameter, now the image is back. Sounds a bit confusing that `hidePostImage = true` shows the post image. Should it not be the other way around? Or does it refer to another typo of image?

Regarding the GitHub action, is there something I can do to help to fix it?

**Comment by binokochumolvarghese** [comment]
You are right and thank you for pointing out. 

I have updated the parameter as `showPostImage`. If its `true` the image will show and vice versa.  Please pull the latest theme.

**Comment by mmartinortiz** [comment]
Thanks @binokochumolvarghese for your help. I updated to the latest version and everything looks perfect.

The deployment issue was solved matching the Hugo versions I had in my GitHub Actions and my local development environment.
